### ISSUE TITLE
Update color scheme & styles for store

### ISSUE THREAD

**Issue by gwenf** [TheJaredWilcurt/product-and-cart#9]

**Comment by TheJaredWilcurt** [comment]
I'm thinking of this one:

* https://www.colourlovers.com/palette/1316015/Rocked_Out

top nav green and light green on hover.

footer maroon

**Comment by TheJaredWilcurt** [comment]
`#79A206` nav
`#9ABA00` nav hover
`#FCF5D8` body bg
`#5B2A3F` footer
`#390D04` body text
`#280D14` card text

Cards/Section Borders/BG
`#FAF2C3` `#F8ED94` `#F6E57B` `#D4D600`
